Minor code improvements
rism-ch/verovio pull request #1639
Opened 2020-08-25 17:22 UTC by alexgnt

- passing string parameters by const ref. in iomusxml and optimization
of convert functions
- removed not needed call of AlignVertically for system aligner

2020-08-25 17:28 UTC, rettinghaus approved these changes

2020-08-27 07:39 UTC, alexgnt commented
@lpugin , please have a look at this one.

2020-08-27 12:43 UTC, craigsapp commented
Looks great to me, although @lpugin can comment about the use of static variables, which he was complaining about in another recent pull request.

2020-08-27 12:46 UTC, lpugin requested changes
Looks good. Please run clang-format.

2020-08-27 12:46 UTC, lpugin commented on src/iomusxml.cpp
> +    if (result != Accidental2Accid.end())
Put on one line or add {} (Same elsewhere)

2020-08-27 13:46 UTC, alexgnt commented on src/iomusxml.cpp
> +    if (result != Accidental2Accid.end())
Done

2020-08-27 13:48 UTC, alexgnt commented
> Looks good. Please run clang-format.

I've fixed only if () {} formatting, since clang, tries to put initialization list on the line value-by-value. What makes it harder to read it, as for me.

2020-08-27 14:24 UTC, lpugin commented
> > Looks good. Please run clang-format.
>
> I've fixed only if () {} formatting, since clang, tries to put initialization list on the line value-by-value. What makes it harder to read it, as for me.

Yes, I know, clang formatting can be annoying in some cases. You can try to see if there are some options we can change in our clang-format configuration. Run it anyway.

2020-08-27 16:37 UTC, alexgnt commented
> > > Looks good. Please run clang-format.
> > 
> > 
> > I've fixed only if () {} formatting, since clang, tries to put initialization list on the line value-by-value. What makes it harder to read it, as for me.
> 
> Yes, I know, clang formatting can be annoying in some cases. You can try to see if there are some options we can change in our clang-format configuration. Run it anyway.

This has been done.

2020-08-28 06:36 UTC, lpugin commented
OK, I looked at it. You can actually do
```
    // clang-format off
    static const std::map<float, data_ACCIDENTAL_GESTURAL> Alter2Accid {
        { -2, ACCIDENTAL_GESTURAL_ff },
        { -1.5, ACCIDENTAL_GESTURAL_fd },
        { -1, ACCIDENTAL_GESTURAL_f },
        { -0.5, ACCIDENTAL_GESTURAL_fu },
        { 0, ACCIDENTAL_GESTURAL_n },
        { 0.5, ACCIDENTAL_GESTURAL_sd },
        { 1, ACCIDENTAL_GESTURAL_s },
        { 1.5, ACCIDENTAL_GESTURAL_su },
        { 2, ACCIDENTAL_GESTURAL_ss }
    };
    // clang-format on
```
or
```
    static const std::map<float, data_ACCIDENTAL_GESTURAL> Alter2Accid{
        { -2, ACCIDENTAL_GESTURAL_ff }, //
        { -1.5, ACCIDENTAL_GESTURAL_fd }, //
        { -1, ACCIDENTAL_GESTURAL_f }, //
        { -0.5, ACCIDENTAL_GESTURAL_fu }, //
        { 0, ACCIDENTAL_GESTURAL_n }, //
        { 0.5, ACCIDENTAL_GESTURAL_sd }, //
        { 1, ACCIDENTAL_GESTURAL_s }, //
        { 1.5, ACCIDENTAL_GESTURAL_su }, //
        { 2, ACCIDENTAL_GESTURAL_ss } //
    };
```

2020-08-28 06:39 UTC, lpugin commented
The second option is probably better because other formatting steps (e.g., tabulations) are still applied. Only line breaks formatting is suppressed.

2020-08-28 10:03 UTC, alexgnt commented
> The second option is probably better because other formatting steps (e.g., tabulations) are still applied. Only line breaks formatting is suppressed.

Done.

2020-08-28 10:05 UTC, lpugin approved these changes

2020-08-28 10:05 UTC, merged