Automatic rest collision avoidance for two layers Mk.2
rism-ch/verovio pull request #1652
Opened 2020-08-31 10:27 UTC by Monceber

Improved performance compared to the previous implementation. About 56 pages of rests are now rendered in ~2.4 seconds compared to previous 75 seconds. Same is rendered in ~1 second without changes, but I think it's the most amount of improvements one can get from this.

Regarding our previous conversation about options - would you rather have none at all and have configurations hardcoded in the map of maps, or would you be fine if json options were to be parsed into such map?

2020-08-31 10:28 UTC, Monceber commented
@lpugin 
Regarding our previous conversation about options - would you rather have none at all and have configurations hardcoded in the map of maps (as in yout example), or would you be fine if json options were to be parsed into such map?

2020-09-01 08:08 UTC, lpugin commented
This looks much better. Speed seems to be fine on the example I previously tested with.

I had a look at the `dyanmic_cast` vs `static_cast` question. Please have a look at this https://github.com/rism-ch/verovio/commit/6c9aab66d4a7e63f6c33b74172d6080af3a0eb9b#commitcomment-41935904 Comments are welcome.

Regarding the map values and the option, we should go for the map of maps following the example I gave. I have not looked at enough examples to understand what the implication it would have to have the values hard-coded and not changeable with an option. If feel it should be OK for now. If you think it is necessary to have the option now, then we can look at what is the best way to parse the JSON for such things with as less code as possible (see https://gist.github.com/lpugin/2b11de6faaf67affe3fcf4b12097b428).

On thing that came to my mind is that it could be good to have some sort of schema users can have in hand to make sure the values they pass with such options are valid. This can be quite helpful. This can open the door to have the code for reading (and writing?) them generated from the Schema. This would be very much MEI / Verovio like. Of course, it can be based on a JSON Schema for the options instead of XML. This might be over the top for one option, though. Opinions on this?

2020-09-02 13:59 UTC, Monceber commented
Went with hardcoded map of map for the time being. Using XML/Json schema to generate code is interesting idea, but I agree a decent amount of options will be needed to warrant adding this.

2020-09-02 15:38 UTC, lpugin requested changes

2020-09-02 15:38 UTC, lpugin commented on include/vrv/functorparams.h
> +
Order alphabetically within the list of FunctorParams subclasses

2020-09-02 15:38 UTC, lpugin commented on include/vrv/options.h
> +#include "jsonxx.h"
This can be removed for now

2020-09-02 15:38 UTC, lpugin commented on include/vrv/options.h
> +    bool m_isSet;
Can be removed too?

2020-09-02 15:38 UTC, lpugin commented on src/layerelement.cpp
> +        : static_cast<Chord *>(GetParent())->GetAlignmentDuration(params->m_mensur, params->m_meterSig);
This will need to be a `vrv_cast` once merged with the latest version of develop. Not sure what is the best way to resolve it.

2020-09-02 15:38 UTC, lpugin commented on src/layerelement.cpp
> +    LayerElementsInTimeSpanParams *params = static_cast<LayerElementsInTimeSpanParams *>(functorParams);
Will now be a `vrv_params_cast`

2020-09-02 15:38 UTC, lpugin commented on src/layerelement.cpp
> +    Layer *currentLayer = static_cast<Layer *>(GetFirstAncestor(LAYER));
Will now be a `vrv_cast`

2020-09-02 18:05 UTC, merged