Improving two-layer note and chord positioning
rism-ch/verovio pull request #1759
Opened 2020-10-19 12:27 UTC by rettinghaus

before:
![issue04](https://user-images.githubusercontent.com/7693447/96450818-fe4d6e80-1216-11eb-954e-6d05b4cb5773.png)
after:
![issue04](https://user-images.githubusercontent.com/7693447/96449207-d0ffc100-1214-11eb-88d6-8cf1edea09bf.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0" ?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron" ?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Single notes against chords</title>
            </titleStmt>
            <pubStmt>
                <respStmt>
                    <persName role="encoder">Klaus Rettinghaus</persName>
                    <corpName role="funder">eNote GmbH</corpName>
                </respStmt>
                <date isodate="2020">2020</date>
            </pubStmt>
            <seriesStmt>
                <title>Verovio test suite</title>
            </seriesStmt>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" lines="5" />
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure right="dbl">
                            <staff n="1">
                                <layer n="1">
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                </layer>
                                <layer n="2">
                                    <note dur="4" oct="5" pname="e" />
                                    <note dur="4" oct="5" pname="c" />
                                    <note dur="4" oct="4" pname="a" />
                                    <note dur="4" oct="4" pname="f" />
                                    <note dur="4" oct="4" pname="d" />
                                    <note dur="4" oct="4" pname="b" />
                                    <note dur="4" oct="4" pname="e" />
                                    <note dur="4" oct="4" pname="c" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                    <section>
                        <measure right="dbl">
                            <staff n="1">
                                <layer n="1">
                                    <note dur="4" oct="5" pname="e" />
                                    <note dur="4" oct="5" pname="c" />
                                    <note dur="4" oct="4" pname="a" />
                                    <note dur="4" oct="4" pname="f" />
                                    <note dur="4" oct="4" pname="d" />
                                    <note dur="4" oct="4" pname="b" />
                                    <note dur="4" oct="4" pname="e" />
                                    <note dur="4" oct="4" pname="c" />
                                </layer>
                                <layer n="2">
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="5" pname="c" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                    <chord dur="4">
                                        <note oct="4" pname="b" />
                                        <note oct="4" pname="e" />
                                    </chord>
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
before:
![issue06](https://user-images.githubusercontent.com/7693447/96450676-cc3c0c80-1216-11eb-92dd-94e6cc942ee1.png)
after:
![issue06](https://user-images.githubusercontent.com/7693447/96449644-73b83f80-1215-11eb-8364-d1eeaa13370a.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0" ?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron" ?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title>Layers with chords sharing noteheads</title>
      </titleStmt>
      <pubStmt>
        <respStmt>
  [...]

2020-10-19 16:14 UTC, craigsapp commented
Looks good, although I notice that these two stems are too close together (second chord in firsts example):

<img width="29" alt="Screen Shot 2020-10-19 at 9 08 18 AM" src="https://user-images.githubusercontent.com/3487289/96476862-a4cf4a80-11ea-11eb-819b-594626bbc93e.png">

But others are correct (such as 6th chord in first example):

<img width="30" alt="Screen Shot 2020-10-19 at 9 10 28 AM" src="https://user-images.githubusercontent.com/3487289/96477107-f1b32100-11ea-11eb-9828-5695b4166050.png">

2020-10-21 08:03 UTC, lpugin requested changes

2020-10-21 08:03 UTC, lpugin commented on include/vrv/layerelement.h
> +#include <set>
Put system includes seprately. See https://github.com/rism-ch/verovio/blob/master/doc/guidelines.md#includes-and-forward-declarations

2020-10-21 08:03 UTC, lpugin commented on src/layerelement.cpp
> +        return ((*firstChord.rbegin() >= *secondChord.rbegin()) && (*firstChord.begin() >= *secondChord.begin()));
Add {}

2020-10-21 08:16 UTC, lpugin approved these changes

2020-10-21 08:16 UTC, merged